### ISSUE TITLE
ModuleNotFoundError: No module named 'SocketServer'

### ISSUE THREAD

**Issue by PraveenChordia** [jfernandz/pyst2#65]
`from asterisk import fastagi`

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/ubuntu/.local/lib/python3.8/site-packages/asterisk/fastagi.py", line 17, in <module>
    import SocketServer
ModuleNotFoundError: No module named 'SocketServer'

**Comment by PraveenChordia** [comment]
```
# Import the correct socket server module
import sys
# Check Python version
PY2 = sys.version_info[0] == 2

# Import the correct socket server module
if PY2:
    import SocketServer  # Python 2
else:
    import socketserver as SocketServer  # Python 3

```
I did this in the FastAGI module and the issue was solved
